import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  Package,
} from "lucide-react";

import PaginationBar from "../../components/PaginationBar";
import ReportKpiGrid from "../../components/reports/ReportKpiGrid";
import ReportPageShell from "../../components/reports/ReportPageShell";
import EmptyState from "../../components/EmptyState";
import { TableSkeleton } from "../../components/Skeleton";
import { StatusBadge } from "../../components/ui";
import FilterBar, { FilterField } from "../../components/ui/FilterBar";
import type { GrnListRow } from "../../api/purchasing";
import { DASHBOARD_QUERY_OPTIONS } from "../../api/queryPresets";
import { useClientPagination } from "../../hooks/usePagination";
import type { ExportColumn } from "../../utils/export";
import { formatDate } from "../../utils/format";
import {
  fetchReportGrns,
  isGrnOverdue,
  isGrnToday,
} from "../../utils/reports/operationalReportData";

export default function GrnReportPage() {
  const [status, setStatus] = useState("");
  const [supplier, setSupplier] = useState("");

  const query = useQuery({
    queryKey: ["operational-report-grn"],
    queryFn: async () => {
      const rows = await fetchReportGrns();
      return { rows, fetchedAt: new Date().toISOString() };
    },
    ...DASHBOARD_QUERY_OPTIONS,
  });

  const allRows = query.data?.rows ?? [];
  const filtered = useMemo(() => {
    return allRows.filter((g) => {
      if (status && (g.status || "") !== status) return false;
      if (supplier) {
        const s = g.supplier_name || g.supplier || "";
        if (s !== supplier) return false;
      }
      return true;
    });
  }, [allRows, status, supplier]);

  const kpis = useMemo(() => {
    const pending = allRows.filter(
      (g) => (g.status || "").toLowerCase() !== "completed",
    ).length;
    const completed = allRows.filter(
      (g) => (g.status || "").toLowerCase() === "completed",
    ).length;
    const overdue = allRows.filter(isGrnOverdue).length;
    const today = allRows.filter(isGrnToday).length;
    return [
      {
        key: "pending",
        label: "Pending GRNs",
        value: String(pending),
        icon: Package,
        tone: { bg: "bg-[#EDE9FE]", fg: "text-[#7C3AED]" },
      },
      {
        key: "completed",
        label: "Completed GRNs",
        value: String(completed),
        icon: CheckCircle2,
        tone: { bg: "bg-[#DCFCE7]", fg: "text-[#16A34A]" },
      },
      {
        key: "overdue",
        label: "Overdue GRNs",
        value: String(overdue),
        icon: AlertTriangle,
        tone: { bg: "bg-[#FEE2E2]", fg: "text-[#DC2626]" },
      },
      {
        key: "today",
        label: "Today's GRNs",
        value: String(today),
        icon: Clock,
        tone: { bg: "bg-[#E8F4FF]", fg: "text-[#1993FF]" },
      },
    ];
  }, [allRows]);

  const suppliers = useMemo(
    () =>
      Array.from(
        new Set(
          allRows.map((r) => r.supplier_name || r.supplier).filter(Boolean),
        ),
      ).sort(),
    [allRows],
  );
  const statuses = useMemo(
    () =>
      Array.from(new Set(allRows.map((r) => r.status).filter(Boolean) as string[])).sort(),
    [allRows],
  );

  const {
    currentPage,
    pageSize,
    setPage,
    setPageSize,
    totalRecords,
    totalPages,
    pageRows,
  } = useClientPagination(filtered, {
    defaultPageSize: 25,
    resetKey: `${status}|${supplier}`,
  });

  const exportColumns = useMemo<ExportColumn<GrnListRow>[]>(
    () => [
      { id: "name", label: "GRN Number", accessor: (r) => r.name },
      {
        id: "po",
        label: "PO Number",
        accessor: (r) => r.purchase_order || "",
      },
      {
        id: "supplier",
        label: "Supplier",
        accessor: (r) => r.supplier_name || r.supplier || "",
      },
      {
        id: "warehouse",
        label: "Warehouse",
        accessor: (r) => r.warehouse || r.set_warehouse || "",
      },
      {
        id: "expected",
        label: "Expected Date",
        accessor: (r) => r.posting_date || "",
      },
      {
        id: "received",
        label: "Received Date",
        accessor: (r) => r.posting_date || "",
      },
      { id: "status", label: "Status", accessor: (r) => r.status || "" },
    ],
    [],
  );

  return (
    <ReportPageShell
      title="GRN Report"
      subtitle="View Goods Receipt Notes generated by Warehouse."
      badge="READ ONLY"
      lastUpdated={query.data?.fetchedAt}
      loading={query.isFetching}
      onRefresh={() => void query.refetch()}
      exportModule="GRN Report"
      exportFilename="GRN_Report"
      exportColumns={exportColumns}
      exportRows={filtered}
      kpis={
        <ReportKpiGrid
          items={kpis}
          loading={query.isLoading}
          columnsClassName="grid-cols-2 md:grid-cols-4"
        />
      }
      filters={
        <FilterBar>
          <div className="flex flex-wrap items-end gap-3">
            <FilterField label="Status">
              <select
                className="select-field"
                value={status}
                onChange={(e) => setStatus(e.target.value)}
              >
                <option value="">All</option>
                {statuses.map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
            </FilterField>
            <FilterField label="Supplier">
              <select
                className="select-field"
                value={supplier}
                onChange={(e) => setSupplier(e.target.value)}
              >
                <option value="">All</option>
                {suppliers.map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
            </FilterField>
            <button
              type="button"
              className="btn-secondary"
              onClick={() => {
                setStatus("");
                setSupplier("");
              }}
            >
              Reset
            </button>
          </div>
        </FilterBar>
      }
    >
      <section className="overflow-hidden rounded-2xl border border-[#E8EDF5] bg-white shadow-[0_1px_3px_rgba(15,23,42,0.04)]">
        <div className="overflow-x-auto">
          {query.isLoading ? (
            <div className="p-4">
              <TableSkeleton rows={8} columns={7} />
            </div>
          ) : pageRows.length === 0 ? (
            <EmptyState
              title="No GRNs"
              description="Warehouse goods receipts will appear here when available."
            />
          ) : (
            <table className="w-full min-w-[860px] text-left">
              <thead className="bg-[#F8FAFC]">
                <tr className="text-[10px] font-semibold uppercase tracking-wider text-neutral-400">
                  <th className="px-4 py-2.5">GRN Number</th>
                  <th className="px-3 py-2.5">PO Number</th>
                  <th className="px-3 py-2.5">Supplier</th>
                  <th className="px-3 py-2.5">Warehouse</th>
                  <th className="px-3 py-2.5">Expected Date</th>
                  <th className="px-3 py-2.5">Received Date</th>
                  <th className="px-3 py-2.5">Status</th>
                  <th className="px-4 py-2.5 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#F1F5F9]">
                {pageRows.map((grn) => {
                  const overdue = isGrnOverdue(grn);
                  return (
                    <tr
                      key={grn.name}
                      className={`text-[12px] ${overdue ? "bg-orange-50/40" : "hover:bg-[#F8FAFC]/80"}`}
                    >
                      <td className="px-4 py-3 font-semibold text-neutral-800">
                        {grn.name}
                      </td>
                      <td className="px-3 py-3 text-neutral-700">
                        {grn.purchase_order || "—"}
                      </td>
                      <td className="px-3 py-3">
                        {grn.supplier_name || grn.supplier || "—"}
                      </td>
                      <td className="px-3 py-3 text-neutral-600">
                        {grn.warehouse || grn.set_warehouse || "—"}
                      </td>
                      <td className="whitespace-nowrap px-3 py-3">
                        <div className="flex flex-col gap-1">
                          {overdue ? (
                            <span className="w-fit rounded-full bg-red-50 px-2 py-0.5 text-[10px] font-semibold uppercase text-red-700 ring-1 ring-red-200">
                              Overdue
                            </span>
                          ) : null}
                          <span className="text-neutral-500">
                            {grn.posting_date
                              ? formatDate(grn.posting_date, "MMM d, yyyy")
                              : "—"}
                          </span>
                        </div>
                      </td>
                      <td className="whitespace-nowrap px-3 py-3 text-neutral-500">
                        {grn.posting_date
                          ? formatDate(grn.posting_date, "MMM d, yyyy")
                          : "—"}
                      </td>
                      <td className="px-3 py-3">
                        {grn.status ? (
                          <StatusBadge status={grn.status} size="sm" />
                        ) : (
                          "—"
                        )}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <Link
                          to={`/p2p/grn/${encodeURIComponent(grn.name)}`}
                          className="text-[11px] font-semibold text-primary-600 hover:underline"
                        >
                          View
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </div>
        <div className="border-t border-[#F1F5F9] px-3 py-2">
          <PaginationBar
            currentPage={currentPage}
            totalPages={totalPages}
            totalRecords={totalRecords}
            pageSize={pageSize}
            onPageChange={setPage}
            onPageSizeChange={setPageSize}
            recordLabel="GRNs"
          />
        </div>
      </section>
    </ReportPageShell>
  );
}
