import { useMemo } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import type { LucideIcon } from "lucide-react";
import {
  ClipboardList,
  Download,
  Package,
  RefreshCw,
  ShoppingCart,
  Truck,
  Users,
} from "lucide-react";

import { DASHBOARD_QUERY_OPTIONS } from "../../api/queryPresets";
import {
  fetchReportGrns,
  fetchReportPurchaseOrders,
  isOpenPoStatus,
} from "../../utils/reports/operationalReportData";
import { formatDateTime } from "../../utils/format";
import { Skeleton } from "../../components/Skeleton";

const CARDS: Array<{
  key: string;
  title: string;
  description: string;
  to: string;
  icon: LucideIcon;
  badge?: string;
  countFrom: "pos" | "openPos" | "deliveries" | "grns" | "suppliers";
}> = [
  {
    key: "po",
    title: "Purchase Order Report",
    description:
      "Analyze all Purchase Orders by supplier, status and buyer.",
    to: "/reports/operations/purchase-orders",
    icon: ShoppingCart,
    countFrom: "pos",
  },
  {
    key: "status",
    title: "PO Status Report",
    description:
      "Track Draft, Open, Approved and Completed Purchase Orders.",
    to: "/reports/operations/po-status",
    icon: ClipboardList,
    countFrom: "openPos",
  },
  {
    key: "delivery",
    title: "Delivery Report",
    description: "Monitor supplier deliveries and expected arrival dates.",
    to: "/reports/operations/deliveries",
    icon: Truck,
    countFrom: "deliveries",
  },
  {
    key: "grn",
    title: "GRN Report",
    description: "View Goods Receipt Notes generated by Warehouse.",
    to: "/reports/operations/grn",
    icon: Package,
    badge: "READ ONLY",
    countFrom: "grns",
  },
  {
    key: "supplier",
    title: "Supplier Performance Report",
    description:
      "Analyze supplier delivery, quality and response performance.",
    to: "/reports/operations/supplier-performance",
    icon: Users,
    countFrom: "suppliers",
  },
];

export default function OperationalReportsPage() {
  const sourceQuery = useQuery({
    queryKey: ["operational-reports-hub"],
    queryFn: async () => {
      const [poResult, grns] = await Promise.all([
        fetchReportPurchaseOrders(),
        fetchReportGrns(),
      ]);
      return { pos: poResult.rows, grns, fetchedAt: new Date().toISOString() };
    },
    ...DASHBOARD_QUERY_OPTIONS,
  });

  const counts = useMemo(() => {
    const pos = sourceQuery.data?.pos ?? [];
    const grns = sourceQuery.data?.grns ?? [];
    const deliveries = pos.filter((p) => isOpenPoStatus(p.status));
    const suppliers = new Set(pos.map((p) => p.supplier).filter(Boolean)).size;
    return {
      pos: pos.length,
      openPos: deliveries.length,
      deliveries: deliveries.length,
      grns: grns.length,
      suppliers,
    };
  }, [sourceQuery.data]);

  const lastUpdated = sourceQuery.data?.fetchedAt;

  return (
    <div className="flex w-full flex-col gap-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <h1 className="text-[22px] font-semibold tracking-tight text-[#111827]">
            Operational Reports
          </h1>
          <p className="mt-1.5 max-w-2xl text-[13px] leading-relaxed text-[#64748B]">
            Analyze Purchase Orders, Deliveries, GRNs and Supplier Performance.
          </p>
          <p className="mt-2 text-[11px] text-neutral-400">
            Last updated{" "}
            {lastUpdated ? formatDateTime(lastUpdated) : "—"}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={() => void sourceQuery.refetch()}
            disabled={sourceQuery.isFetching}
            className="inline-flex items-center gap-1.5 rounded-xl border border-[#E8EDF5] bg-white px-3 py-2 text-[12px] font-semibold text-neutral-700 shadow-sm transition hover:bg-neutral-50 disabled:opacity-50"
          >
            <RefreshCw
              className={`h-3.5 w-3.5 ${sourceQuery.isFetching ? "animate-spin" : ""}`}
            />
            Refresh
          </button>
          <Link
            to="/reports/operations/purchase-orders"
            className="inline-flex items-center gap-1.5 rounded-xl border border-[#E8EDF5] bg-white px-3 py-2 text-[12px] font-semibold text-neutral-700 no-underline shadow-sm transition hover:bg-neutral-50"
          >
            <Download className="h-3.5 w-3.5" />
            Export
          </Link>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
        {CARDS.map((card) => {
          const Icon = card.icon;
          const count = counts[card.countFrom];
          return (
            <div
              key={card.key}
              className="flex min-h-[200px] flex-col rounded-2xl border border-[#E8EDF5] bg-white p-4 shadow-[0_1px_3px_rgba(15,23,42,0.04)] transition hover:-translate-y-0.5 hover:shadow-[0_4px_12px_rgba(15,23,42,0.07)]"
            >
              <div className="flex items-start justify-between gap-3">
                <span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-50 text-primary-700">
                  <Icon className="h-4 w-4" />
                </span>
                {card.badge ? (
                  <span className="rounded-full bg-neutral-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-neutral-600 ring-1 ring-neutral-200">
                    {card.badge}
                  </span>
                ) : null}
              </div>
              <h2 className="mt-3 text-[15px] font-semibold text-[#111827]">
                {card.title}
              </h2>
              <p className="mt-1 flex-1 text-[12px] leading-relaxed text-[#64748B]">
                {card.description}
              </p>
              <div className="mt-3 flex items-center justify-between gap-3 border-t border-[#F1F5F9] pt-3">
                <div>
                  <p className="text-[10px] font-medium uppercase tracking-wider text-neutral-400">
                    Records
                  </p>
                  {sourceQuery.isLoading ? (
                    <Skeleton className="mt-1 h-5 w-10" />
                  ) : (
                    <p className="text-[16px] font-bold tabular-nums text-[#0F172A]">
                      {count.toLocaleString()}
                    </p>
                  )}
                  <p className="mt-0.5 text-[10px] text-neutral-400">
                    Last updated{" "}
                    {lastUpdated ? formatDateTime(lastUpdated) : "—"}
                  </p>
                </div>
                <Link
                  to={card.to}
                  className="shrink-0 rounded-xl bg-primary px-3 py-2 text-[12px] font-semibold text-white no-underline transition hover:bg-primary-600"
                >
                  Open Report →
                </Link>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
