import { Navigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import InvoiceDetailPage from "../p2p/InvoiceDetailPage";
import InvoiceWorkflowDetailPage from "./InvoiceWorkflowDetailPage";
import { findVoucherByInvoiceNumber } from "../../api/vouchers";
import EmptyState from "../../components/EmptyState";
import { Receipt } from "lucide-react";

/**
 * Routes invoice detail by ID type:
 * - Voucher workflow IDs (`VCH-YYYY-NNNNN` — the ERPNext "Voucher" DocType's
 *   fixed autoname pattern) → finance voucher invoice review, loaded
 *   directly by Voucher name.
 * - A bare supplier invoice number (e.g. `INV-SUMMIT-0594`, generated by the
 *   supplier at submission time and stored only inside the parent Voucher's
 *   `invoice_json`) → resolved to its owning Voucher first, then redirected
 *   to the canonical `/p2p/invoices/VCH-...` URL. It is NEVER looked up as a
 *   `Purchase Invoice` name.
 * - Everything else (genuine ERPNext `Purchase Invoice` names, e.g.
 *   `ACC-PINV-*`) → live Purchase Invoice detail.
 *
 * The VCH- branch MUST be a synchronous, ID-shape decision — not a "try
 * fetching the Voucher first, fall back if it looks empty" guess. A
 * trial-fetch approach previously lived here and was unreliable: any
 * transient error, permission hiccup, or stale React Query cache entry would
 * make `voucher.invoice` look empty, silently fall through to the Purchase
 * Invoice lookup with a Voucher ID, 404, and render a misleading "Invoice
 * not found" even though the invoice genuinely existed in ERPNext. Deciding
 * purely from the ID's naming-series prefix removes that entire
 * race/cache-staleness class of bug for the common case (Review button,
 * which always passes the Voucher name).
 */
export default function InvoiceDetailRoutePage() {
  const { id = "" } = useParams();
  const invoiceId = decodeURIComponent(id);

  console.info(`[Invoice Route] Incoming route parameter: "${invoiceId}"`);

  if (/^VCH-/i.test(invoiceId)) {
    console.info(
      `[Invoice Route] "${invoiceId}" matches the Voucher naming series -> loading Voucher directly.`
    );
    return <InvoiceWorkflowDetailPage />;
  }

  return <InvoiceNumberResolver invoiceNumber={invoiceId} />;
}

/**
 * Handles bare invoice-number URLs (STEP 5/STEP 4 of the invoice lookup
 * audit): resolve the owning Voucher server-side before deciding where to
 * render, instead of guessing from the URL shape alone.
 */
function InvoiceNumberResolver({ invoiceNumber }: { invoiceNumber: string }) {
  const {
    data: voucher,
    isLoading,
    isError,
    error,
  } = useQuery({
    queryKey: ["voucher-by-invoice-number", invoiceNumber],
    queryFn: () => findVoucherByInvoiceNumber(invoiceNumber),
    enabled: !!invoiceNumber,
    staleTime: 30_000,
  });

  if (isLoading) {
    return (
      <EmptyState icon={Receipt} title="Loading invoice…" description="" />
    );
  }

  if (isError) {
    console.error(
      `[Invoice Route] ERP query failed while resolving invoice number "${invoiceNumber}":`,
      error
    );
    return (
      <EmptyState
        icon={Receipt}
        title="Could not load this invoice"
        description={
          error instanceof Error
            ? error.message
            : "The server returned an error while resolving this invoice. Please retry."
        }
      />
    );
  }

  if (voucher) {
    console.info(
      `[Invoice Route] Resolved invoice number "${invoiceNumber}" -> Voucher "${voucher.id}". Redirecting to canonical URL.`
    );
    return (
      <Navigate to={`/p2p/invoices/${encodeURIComponent(voucher.id)}`} replace />
    );
  }

  console.info(
    `[Invoice Route] "${invoiceNumber}" did not resolve to any Voucher-linked invoice -> treating as a Purchase Invoice name.`
  );
  return <InvoiceDetailPage />;
}
